# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define  "rm1"
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "file", source: "slurm.conf", destination: "/tmp/slurm.conf"
  config.vm.provision "shell" do |s|
    s.privileged = true,
    s.inline = %q(
      yum install -y epel-release
      rpm -i https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm
      yum install -y slurm-slurmctld-ohpc slurm-slurmd-ohpc slurm-example-configs-ohpc
      cp -v /tmp/slurm.conf /etc/slurm/slurm.conf
      systemctl enable --now munge
      systemctl restart slurmctld slurmd
    )
  end
end

