# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define  "rm1"
  config.vm.box = "centos/8"
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "file", source: "slurm.conf", destination: "/tmp/slurm.conf"
  config.vm.provision "shell" do |s|
    s.privileged = true,
    s.inline = %q(
      yum install -y epel-release
      rpm -i http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm
      yum install -y slurm-slurmctld-ohpc slurm-slurmd-ohpc slurm-example-configs-ohpc
      cp -v /tmp/slurm.conf /etc/slurm/slurm.conf
      systemctl enable --now munge
      systemctl restart slurmctld slurmd
    )
  end
end

